import streamlit as st
import pandas as pd
from PIL import Image
import io
import plotly.express as px
from supabase import create_client, Client
from datetime import datetime
import requests 
import traceback
import base64
from fpdf import FPDF 

# --- API URL (Local Backend) ---
BACKEND_URL = "http://127.0.0.1:8000/predict/"

# --- PAGE CONFIG ---
st.set_page_config(page_title="InSight: Cataract Screening", layout="wide")

# --- CUSTOM CSS ---
st.markdown("""
<style>
    html, body, [class*="st-"], [class*="css-"] { font-family: 'Source Sans Pro', sans-serif; }
    .stButton>button { margin-top: 10px; margin-bottom: 10px; }
    .stAlert { border-radius: 8px; }
</style>
""", unsafe_allow_html=True)

# --- SUPABASE CONNECTION ---
@st.cache_resource
def init_supabase_client():
    try:
        url = st.secrets["SUPABASE_URL"]
        key = st.secrets["SUPABASE_KEY"]
        return create_client(url, key)
    except:
        st.error("❌ Supabase secrets not found. Please check .streamlit/secrets.toml")
        return None

supabase = init_supabase_client()

# --- PDF HELPER (Robust Fix) ---
def create_screening_report(patient_id, prediction, confidence, recommendation, screened_by, original_image_bytes, overlay_bytes, original_image_type_mime):
    pdf = FPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)
    
    # Title
    pdf.set_font("Times", "B", 20)
    pdf.cell(0, 10, "InSight Ocular Screening Report", 0, 1, "C")
    pdf.ln(5)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(10)
    
    # Info
    pdf.set_font("Times", "B", 14)
    pdf.cell(0, 10, "Patient Information", 0, 1, "L")
    pdf.set_font("Times", "", 12)
    pdf.cell(50, 8, "Patient Identifier:", 0, 0, "L")
    pdf.cell(0, 8, f"{patient_id}", 0, 1, "L")
    pdf.cell(50, 8, "Screening Date:", 0, 0, "L")
    pdf.cell(0, 8, f"{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", 0, 1, "L")
    pdf.cell(50, 8, "Screened By:", 0, 0, "L")
    pdf.cell(0, 8, f"{screened_by}", 0, 1, "L")
    pdf.ln(10)

    # Results
    pdf.set_font("Times", "B", 14)
    pdf.cell(0, 10, "Ocular Screening Analysis", 0, 1, "L")
    pdf.set_font("Times", "B", 12)
    pdf.cell(50, 8, "Assessment:", 0, 0, "L")
    
    if prediction == "Cataract Detected":
        pdf.set_text_color(220, 53, 69) # Red
    else:
        pdf.set_text_color(25, 135, 84) # Green
        
    pdf.cell(0, 8, f"{prediction}", 0, 1, "L")
    pdf.set_text_color(0, 0, 0)
    
    pdf.set_font("Times", "", 12)
    if prediction == "Cataract Detected":
        conf_text = f"{confidence:.1%}"
    else:
        conf_text = f"{1-confidence:.1%}"
    pdf.cell(50, 8, "Confidence Level:", 0, 0, "L")
    pdf.cell(0, 8, conf_text, 0, 1, "L")
    
    pdf.set_font("Times", "B", 12)
    pdf.cell(50, 8, "Recommendation:", 0, 0, "L")
    pdf.set_font("Times", "", 12)
    pdf.cell(0, 8, recommendation, 0, 1, "L")
    pdf.ln(10)

    # Images Section
    pdf.set_font("Times", "B", 14)
    pdf.cell(0, 10, "Analysis Visualization", 0, 1, "L")
    y_images = pdf.get_y()
    
    # 1. Original Image (Left)
    try:
        img_stream = io.BytesIO(original_image_bytes)
        img_stream.seek(0) # Rewind
        
        img_type = "JPG"
        if original_image_type_mime and "png" in original_image_type_mime.lower(): 
            img_type = "PNG"
            
        pdf.image(img_stream, x=10, y=y_images, w=90, type=img_type)
        
        pdf.set_xy(10, y_images + 90)
        pdf.set_font("Times", "", 10)
        pdf.cell(90, 5, "Original Fundus Image", 0, 0, "C")
    except Exception as e: 
        print(f"PDF Original Image Error: {e}")

    # 2. Grad-CAM Image (Right)
    try:
        gc_stream = io.BytesIO(overlay_bytes) # Already bytes from backend
        gc_stream.seek(0) # Rewind
        
        pdf.image(gc_stream, x=110, y=y_images, w=90, type="PNG")
        
        pdf.set_xy(110, y_images + 90)
        pdf.cell(90, 5, "AI Visualization (Grad-CAM)", 0, 0, "C")
    except Exception as e: 
        print(f"PDF Grad-CAM Error: {e}")
    
    # Disclaimer
    pdf.set_y(-35)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(5)
    pdf.set_font("Times", "I", 9)
    pdf.set_text_color(108, 117, 125)
    pdf.multi_cell(0, 5, "DISCLAIMER: This report is generated by an AI-assisted screening tool (InSight). Not a medical diagnosis.", 0, "C")
    
    # --- FIX FOR ATTRIBUTE ERROR ---
    out = pdf.output(dest='S')
    # Check if it's already bytes/bytearray (Py3 FPDF behavior can vary)
    if isinstance(out, (bytes, bytearray)):
        return bytes(out)
    # Otherwise encode string to bytes
    return out.encode('latin-1')

# --- AUTH FUNCTIONS ---
def main_auth_page():
    st.title("InSight Cataract Screening")
    st.write("Please log in or sign up to continue.")
    login_tab, signup_tab = st.tabs(["Login", "Sign Up"])
    
    with login_tab:
        with st.form("login_form"):
            email = st.text_input("Email")
            password = st.text_input("Password", type="password")
            if st.form_submit_button("Login"):
                try:
                    session = supabase.auth.sign_in_with_password({"email": email, "password": password})
                    st.session_state["session"] = session
                    st.session_state["logged_in"] = True
                    
                    user_id = session.user.id
                    role_data = supabase.table('user_roles').select('role').eq('user_id', user_id).single().execute()
                    user_role = "Nurse"
                    if role_data.data and 'role' in role_data.data: user_role = role_data.data['role']
                    st.session_state["user_role"] = user_role
                    st.session_state["user_name"] = session.user.email
                    st.rerun()
                except Exception as e: st.error(f"Login failed: {e}")

    with signup_tab:
        with st.form("signup_form"):
            email = st.text_input("Email")
            password = st.text_input("Password", type="password")
            role = st.selectbox("Role", ("Nurse", "Doctor"))
            if st.form_submit_button("Sign Up"):
                try:
                    session = supabase.auth.sign_up({"email": email, "password": password})
                    if session.user:
                        supabase.table('user_roles').insert({'user_id': session.user.id, 'email': email, 'role': role}).execute()
                        st.success("Signup successful!")
                    else: st.error("Signup failed.")
                except Exception as e: st.error(f"Error: {e}")

def logout():
    supabase.auth.sign_out()
    st.session_state["logged_in"] = False
    st.session_state.pop("session", None)
    st.rerun()

# --- PAGES ---
def screening_page():
    st.title("New Patient Screening")
    st.write("Upload a fundus photograph to screen for cataracts.")
    uploaded_file = st.file_uploader("Upload Fundus Image", type=["jpg", "jpeg", "png"])
    patient_id = st.text_input("Patient Identifier")

    if uploaded_file and patient_id:
        col1, col2 = st.columns(2)
        image_bytes = uploaded_file.getvalue()
        pil_image = Image.open(io.BytesIO(image_bytes))
        
        with col1:
            st.image(pil_image, caption="Uploaded Image", use_container_width=True)

        if st.button("Analyze Image"):
            with col2:
                with st.spinner("Analyzing image... (Connecting to backend)"):
                    try:
                        files = {'file': (uploaded_file.name, image_bytes, uploaded_file.type)}
                        response = requests.post(BACKEND_URL, files=files)
                        response.raise_for_status() 
                        
                        result = response.json()
                        pred_prob = result["prediction_probability"]
                        gc_bytes = base64.b64decode(result["gradcam_image_base64"])

                        if pred_prob > 0.5:
                            label = "Cataract Detected"
                            rec = "Urgent: Refer to Ophthalmologist"
                            st.error(f"**{label}** ({pred_prob:.1%})")
                        else:
                            label = "No Cataract Detected"
                            rec = "Routine Check-up"
                            st.success(f"**{label}** ({1-pred_prob:.1%})")
                        
                        st.warning(f"**Recommendation: {rec}**")
                        st.image(gc_bytes, caption="Grad-CAM Heatmap", use_container_width=True)
                        
                        # Save result to session state for buttons
                        st.session_state["last_res"] = {
                            "pid": patient_id, "label": label, "prob": pred_prob, "rec": rec,
                            "img": image_bytes, "gc": gc_bytes, "mime": uploaded_file.type
                        }
                    except Exception as e: st.error(f"Connection Error: Is backend running? {e}")

        # Show Buttons if result exists
        if "last_res" in st.session_state and st.session_state["last_res"]["pid"] == patient_id:
            res = st.session_state["last_res"]
            c1, c2, c3 = st.columns(3)
            with c1:
                if st.button("Save Results", use_container_width=True):
                    try:
                        supabase.table('screenings').insert({
                            "patient_identifier": res["pid"], "image_filename": uploaded_file.name,
                            "predicted_label": res["label"], "prediction_probability": res["prob"],
                            "recommendation": res["rec"], "screened_by_user": st.session_state["user_name"]
                        }).execute()
                        st.success("Saved results successfully!")
                    except Exception as e: st.error(f"Save failed: {e}")
            
            with c2:
                # Generate PDF
                pdf = create_screening_report(res["pid"], res["label"], res["prob"], res["rec"], st.session_state["user_name"], res["img"], res["gc"], res["mime"])
                st.download_button("Export PDF Report", pdf, f"InSight_Report_{res['pid']}.pdf", "application/pdf", use_container_width=True)
            
            with c3:
                st.download_button("Export Grad-CAM", res["gc"], f"{res['pid']}_gradcam.png", "image/png", use_container_width=True)

def patient_history_page():
    st.title("Patient Screening History")
    st.write("Enter a Patient Identifier to view their past screening results.")
    search_id = st.text_input("Patient Identifier")
    
    if st.button("Search History"):
        if not search_id: st.warning("Please enter a Patient Identifier."); return
        with st.spinner(f"Searching for patient {search_id}..."):
            try:
                query = supabase.table('screenings').select("*").eq('patient_identifier', search_id).order('created_at', desc=True).execute()
                if query.data:
                    df = pd.DataFrame(query.data)
                    df['created_at'] = pd.to_datetime(df['created_at']).dt.strftime('%Y-%m-%d %H:%M:%S')
                    df['prediction_probability'] = df['prediction_probability'].apply(lambda x: f"{x:.1%}" if pd.notna(x) else "N/A")
                    
                    display_df = df[['created_at', 'predicted_label', 'prediction_probability', 'recommendation', 'screened_by_user', 'image_filename']].rename(columns={'created_at': 'Screening Date', 'predicted_label': 'Prediction', 'prediction_probability': 'Confidence', 'recommendation': 'Recommendation', 'screened_by_user': 'Screened By', 'image_filename': 'Original Image'})
                    st.dataframe(display_df, use_container_width=True)
                else:
                    st.info("No records found for this patient.")
            except Exception as e:
                st.error(f"Error fetching history: {e}")

def analytics_page():
    st.title("Analytics Dashboard")
    st.write("Overview of screening metrics. (Only Doctors can see this page)")
    try:
        data = supabase.table('screenings').select("*").execute()
        df = pd.DataFrame(data.data)
    except Exception as e: st.error(f"Error fetching data: {e}"); df = pd.DataFrame()
    
    if df.empty:
        st.warning("No screening data found to display analytics.")
        return
        
    total_screened = len(df)
    total_cataract = len(df[df['predicted_label'] == 'Cataract Detected'])
    percent_cataract = (total_cataract / total_screened) * 100 if total_screened > 0 else 0
    
    col1, col2 = st.columns(2)
    col1.metric("Total Patients Screened", total_screened)
    col2.metric("Cataracts Detected", total_cataract, f"{percent_cataract:.1f}% of total")
    
    st.divider()
    
    col3, col4 = st.columns(2)
    with col3:
        st.subheader("Screenings by Recommendation")
        recommend_counts = df['recommendation'].value_counts()
        fig1 = px.bar(recommend_counts, x=recommend_counts.index, y=recommend_counts.values, labels={'x': 'Recommendation', 'y': 'Count'})
        st.plotly_chart(fig1, use_container_width=True)
        
    with col4:
        st.subheader("Detections by Type")
        label_counts = df['predicted_label'].value_counts()
        fig2 = px.pie(label_counts, names=label_counts.index, values=label_counts.values)
        st.plotly_chart(fig2, use_container_width=True)
        
    st.subheader("Recent Screening Data")
    st.dataframe(df.sort_values(by="created_at", ascending=False).head(10), use_container_width=True)

# --- ROUTER ---
if "logged_in" not in st.session_state: st.session_state["logged_in"] = False
if not st.session_state["logged_in"]: main_auth_page()
else:
    st.sidebar.title("Navigation")
    st.sidebar.write(f"Welcome, **{st.session_state['user_name']}**!")
    st.sidebar.write(f"Role: *{st.session_state['user_role']}*")
    
    opts = ["Screening", "Patient History"]
    if st.session_state["user_role"] == "Doctor": opts.append("Analytics")
    page = st.sidebar.radio("Go to", opts)
    st.sidebar.divider()
    if st.sidebar.button("Logout"): logout()
    
    if page == "Screening": screening_page()
    elif page == "History": patient_history_page()
    elif page == "Analytics": analytics_page()